### ISSUE TITLE
[Submission] Checklist before submitting the Thesis

### ISSUE THREAD

**Issue by NikkelM** [NikkelM/bachelor-thesis#1]
- [x] Add submission date
- [x] Should the title page be translated?
- [x] Add Reviewer names
- [x] Check bibliography
- [x] Run a spellcheck on the whole document
- [x] Make three copies for submission (`\printVersionTrue`)
- [x] Digital copy (pdf)
